#ifndef TASK4_TYPES_OF_LEX_H
#define TASK4_TYPES_OF_LEX_H

enum type_of_lex {LEX_NULL,
	LEX_AND, LEX_BOOL, LEX_STRING, LEX_DO, LEX_ELSE, LEX_IF,
	LEX_FALSE, LEX_INT, LEX_NOT, LEX_OR, LEX_PROGRAM, LEX_READ , 
	LEX_THEN, LEX_TRUE, LEX_VAR, LEX_WHILE, LEX_WRITE, LEX_GOTO,
	LEX_FIN, 
	LEX_SEMICOLON, LEX_DOG, LEX_COMMA, LEX_COLON, LEX_ASSIGN, LEX_OPPAR,
	LEX_CLPAR, LEX_EQ, LEX_L, LEX_G, LEX_PLUS, LEX_MINUS, LEX_MULT,
	LEX_DIV, LEX_LEQ, LEX_NEQ, LEX_GEQ, LEX_DQM, LEX_FIGOP, LEX_FIGCL,LEX_UNMIN,
	LEX_NUM,
        LEX_STRINGCONST,
	LEX_ID,
	POLIZ_LABEL,
	POLIZ_ADDRESS,
	POLIZ_GO, 
	POLIZ_FGO
};
        
#endif //TASK4_TYPES_OF_LEX_H
